# Generated by Django 5.2.4 on 2025-07-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('minutos_tarde', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('justificado', 'Justificado'), ('no_justificado', 'No Justificado')], default='pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
        ),
    ]
