# Generated by Django 5.2.4 on 2025-07-15 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_email_remove_alumno_telefono'),
        ('atrasos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atraso',
            options={'ordering': ['-fecha', 'alumno__nombre_completo'], 'verbose_name': 'Atraso', 'verbose_name_plural': 'Atrasos'},
        ),
        migrations.AddField(
            model_name='atraso',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='atraso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrasos', to='alumnos.alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='atraso',
            unique_together={('alumno', 'fecha')},
        ),
    ]
