# Generated by Django 5.2.4 on 2025-07-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='telefono',
        ),
    ]
