# Generated by Django 5.1.3 on 2025-07-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_remove_alumno_email_remove_alumno_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana", models.IntegerField()),
                ("anio", models.IntegerField()),
                ("acuerdo_con_apoderado", models.BooleanField(default=False)),
                ("compromiso_alumno", models.BooleanField(default=False)),
                ("incumplido", models.BooleanField(default=False)),
                ("veces_incumplido", models.IntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
            ],
            options={
                "unique_together": {("alumno", "semana", "anio")},
            },
        ),
    ]
